import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const schema = defineSchema({
	...authTables,
	kingdoms: defineTable({
		userId: v.string(),
		kdName: v.string(),
		rulerName: v.string(),
		planetType: v.string(),
		raceType: v.string(),
		population: v.number(),
		popChange: v.number(),
		land: v.number(),
		money: v.number(),
		power: v.number(),
		probes: v.number(),
		moneyIncome: v.number(),
		powerIncome: v.number(),
		nw: v.number(),
		autoExplore: v.optional(v.boolean()),
		autoBuild: v.optional(v.boolean()),
		landQueue: v.array(v.number()),
		military: v.object({
			sol: v.number(),
			tr: v.number(),
			dr: v.number(),
			ft: v.number(),
			tf: v.number(),
			lt: v.number(),
			ld: v.number(),
			lf: v.number(),
			f74: v.number(),
			t: v.number(),
			hgl: v.number(),
			ht: v.number(),
			sci: v.number(),
			queue: v.object({
				sol: v.array(v.number()),
				tr: v.array(v.number()),
				dr: v.array(v.number()),
				ft: v.array(v.number()),
				tf: v.array(v.number()),
				lt: v.array(v.number()),
				ld: v.array(v.number()),
				lf: v.array(v.number()),
				f74: v.array(v.number()),
				t: v.array(v.number()),
				hgl: v.array(v.number()),
				ht: v.array(v.number()),
				sci: v.array(v.number()),
			}),
		}),
		buildings: v.object({
			res: v.number(),
			plants: v.number(),
			rax: v.number(),
			sm: v.number(),
			pf: v.number(),
			tc: v.number(),
			asb: v.number(),
			ach: v.number(),
			rubble: v.number(),
			target: v.optional(
				v.object({
					res: v.number(),
					plants: v.number(),
					rax: v.number(),
					sm: v.number(),
					pf: v.number(),
					tc: v.number(),
					asb: v.number(),
					ach: v.number(),
				}),
			),
			queue: v.object({
				res: v.array(v.number()),
				plants: v.array(v.number()),
				rax: v.array(v.number()),
				sm: v.array(v.number()),
				pf: v.array(v.number()),
				tc: v.array(v.number()),
				asb: v.array(v.number()),
				ach: v.array(v.number()),
			}),
		}),
		researchPts: v.number(),
		research: v.object({
			pop: v.object({ pts: v.number(), perc: v.number() }),
			power: v.object({ pts: v.number(), perc: v.number() }),
			mil: v.object({ pts: v.number(), perc: v.number() }),
			money: v.object({ pts: v.number(), perc: v.number() }),
			fdc: v.object({ pts: v.number(), perc: v.number() }),
			warp: v.object({ pts: v.number(), perc: v.number() }),
			dr: v.optional(v.object({ pts: v.number(), perc: v.number() })),
			ft: v.optional(v.object({ pts: v.number(), perc: v.number() })),
			tf: v.optional(v.object({ pts: v.number(), perc: v.number() })),
			ld: v.optional(v.object({ pts: v.number(), perc: v.number() })),
			lf: v.optional(v.object({ pts: v.number(), perc: v.number() })),
			f74: v.optional(v.object({ pts: v.number(), perc: v.number() })),
			hgl: v.optional(v.object({ pts: v.number(), perc: v.number() })),
			ht: v.optional(v.object({ pts: v.number(), perc: v.number() })),
			fusion: v.optional(v.object({ pts: v.number(), perc: v.number() })),
			core: v.optional(v.object({ pts: v.number(), perc: v.number() })),
			armor: v.optional(v.object({ pts: v.number(), perc: v.number() })),
		}),
		researchAutoAssign: v.array(v.string()),
	}).index("by_userId", ["userId"]),
	spyReports: defineTable({
		userId: v.string(),
		targetKdName: v.string(),
		targetRulerName: v.string(),
		targetPlanetType: v.string(),
		targetRaceType: v.string(),
		targetLevel: v.number(),
		land: v.number(),
		networth: v.number(),
		honor: v.number(),
		money: v.number(),
		population: v.number(),
		power: v.number(),
		probes: v.number(),
		scientists: v.number(),
		maProtection: v.number(),
		military: v.object({
			sol: v.number(),
			tr: v.number(),
			dr: v.number(),
			ft: v.number(),
			tf: v.number(),
			lt: v.number(),
			ld: v.number(),
			lf: v.number(),
			f74: v.number(),
			t: v.number(),
			hgl: v.number(),
			ht: v.number(),
		}),
		maxDefPotential: v.number(),
		maxOffPotential: v.number(),
		buildings: v.optional(
			v.object({
				res: v.number(),
				plants: v.number(),
				rax: v.number(),
				sm: v.number(),
				pf: v.number(),
				tc: v.number(),
				asb: v.number(),
				ach: v.number(),
				rubble: v.number(),
				queue: v.object({
					res: v.array(v.number()),
					plants: v.array(v.number()),
					rax: v.array(v.number()),
					sm: v.array(v.number()),
					pf: v.array(v.number()),
					tc: v.array(v.number()),
					asb: v.array(v.number()),
					ach: v.array(v.number()),
				}),
			}),
		),
		spiedAt: v.number(),
	}).index("by_userId", ["userId"]),
	gameStatus: defineTable({
		currentTick: v.number(),
		endTick: v.number(),
		roundNumber: v.number(),
	}),
});

export default schema;
