export const PLANET_TYPES = [
	"Mountainous",
	"Forest and Wilderness",
	"Herbal Jungle",
	"Terra Form",
	"Mystical Lands",
	"Volcanic Inferno",
	"Jagged Tundra",
	"Oceanic",
	"Desert Wasteland",
	"Ice Giant",
	"Shadow Lands",
	"Multiple Terrain",
	"Helium",
	"Eternal Plains",
] as const;

export const RACE_TYPES = [
	"Ancients",
	"Terran",
	"Xivornai",
	"Gistrami",
	"Mafielven",
	"Qanut",
	"Shadow",
] as const;

export const GAME_PARAMS = {
	roundLength: 480,
	income: {
		population: 2,
		sm: 140,
	},
	population: {
		growth: 0.05,
		decline: (pop: number, land: number) =>
			Math.round(Math.max(land / 5, pop * 0.05)),
	},
	power: {
		consumption: {
			population: 0.032,
			scientists: 0.7,
			soldiers: 0.7,
		},
	},
	explore: {
		duration: 24,
		limit: 0.1,
		cost: (land: number) => Math.round(Math.sqrt(land) * 111),
	},
	buildings: {
		duration: 16,
		cost: (land: number) => Math.round(Math.sqrt(land) * 63),
		resCapacity: 50,
		raxCapacity: 75,
		asbCapacity: 40,
		achCapacity: 60,
		plantProduction: 140,
		plantStorage: 1000,
	},
	military: {
		duration: 24,
		soldierDuration: 16,
		soldiersLimit: 0.1,
		units: {
			sol: { cost: 150, power: 0.7, housing: 1 },
			sci: { cost: 1000, power: 0.7, housing: 1 },
			tr: { cost: 350, power: 0.7, housing: 1 },
			dr: { cost: 450, power: 0.7, housing: 1 },
			ft: { cost: 550, power: 0.7, housing: 1 },
			tf: {
				cost: 1500,
				power: 1.4,
				housing: 1,
				requiresBuilding: "asb",
			},
			lt: { cost: 375, power: 0.7, housing: 1 },
			ld: { cost: 500, power: 0.7, housing: 1 },
			lf: { cost: 625, power: 0.7, housing: 1 },
			f74: {
				cost: 975,
				power: 1.4,
				housing: 1,
				requiresBuilding: "ach",
			},
			t: { cost: 1750, power: 1.4, housing: 2 },
			hgl: { cost: 1000, power: 0.7, housing: 1 },
			ht: { cost: 2250, power: 1.4, housing: 2 },
		},
	},
	nw: {
		units: {
			sol: 3,
			tr: 6,
			dr: 8,
			ft: 10,
			tf: 18,
			lt: 6,
			ld: 8,
			lf: 10,
			f74: 12,
			t: 22,
			hgl: 15,
			ht: 31,
			sci: 8,
		},
		land: 25,
		buildings: 25,
		population: 1,
		money: 500,
		probes: 1000,
	},
} as const;
